name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
        <html>           
<head>
<meta charset='utf-8'> 
<link rel='stylesheet'href='style.css'>
</head> 
<body bgcolor=#ED89A1 text =black>
<h1 align=center>Te iubesc motănel!</h1>
<h2>PS. „Ești al meu:) <3” </h2>
<img src="cat love.png"/>
</picture>

</body>
</html>
        
